config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "countries#index"

  resources :countries, only: %i[index show]

  get :search_region, to: "search#search_region"
  get :search_country, to: "search#search_country"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/countries_concern.rb
#frozen_string_literal: true

module CountriesConcern
  extend ActiveSupport::Concern

  included do
    before_action :set_rest_countries

    def all_countries
      Rails.cache.fetch("all_countries_cache", expires_in: 24.hours) do
        @client.all
      end
    end

    def fetch_country(country)
      Rails.cache.fetch("#{country}_cache", expires_in: 24.hours) do
        @client.name(country)
      end
    end

    def fetch_region(region)
      Rails.cache.fetch("#{region}_cache", expires_in: 24.hours) do
        @client.region(region)
      end
    end

    def fetch_code(code)
      Rails.cache.fetch("#{code}_cache", expires_in: 24.hours) do
        @client.code(code)
      end
    end
  end

  private

  def set_rest_countries
    @client = RestCountries::Client.new
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  include CountriesConcern

  def index
    @countries = all_countries
  end

  def show
    @country = fetch_code(params[:id])
  rescue RestCountries::Error => e
    render turbo_stream:
      turbo_stream.prepend("toast", partial: "shared/toast", locals: { message: e.message })
  end

end

app/controllers/search_controller.rb
class SearchController < CountriesController
  def search_region
    query = params[:query]
    if query.downcase == "all"
      @countries = all_countries
    else
      region = URI.encode_www_form_component(query)
      @countries = fetch_region(region)
    end

    if request.path == countries_path
      render turbo_stream:
        turbo_stream.update("countries", partial: "countries", locals: { countries: @countries})
    else
      redirect_to countries_path
    end
  end

  def search_country
    query = params[:query]
    if query.strip.empty?
      @countries = all_countries
    else
      @countries = fetch_country(query)
    end
    render turbo_stream:
      turbo_stream.update("countries", partial: "countries", locals: { countries: @countries})
  rescue RestCountries::Error => e
    render turbo_stream:
      turbo_stream.prepend("toast", partial: "shared/toast", locals: { message: "#{query.capitalize}: #{e.message}" })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_countries.html.erb
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 p-4 pt-28">
  <% countries.each do |country| %>
    <a href="<%= country_path(country["cca2"]) %>" data-turbo="false" class="flex flex-col rounded-lg md:max-w-xl hover:bg-white dark:bg-gray-800 dark:hover:bg-gray-700">
      <img class="object-cover w-full rounded-lg h-60 shadow-xs" src="<%= country["flags"]["svg"] %>" alt="">
      <div class="flex flex-col justify-between p-4 leading-normal">
          <h5 class="mb-2 text-md font-semibold tracking-tight text-gray-900 dark:text-white"><%= country["name"]["official"] %></h5>
          <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= country["continents"][0] %></p>
      </div>
    </a>
  <% end %>
</div>

app/views/countries/_country.html.erb
<div class="flex flex-col p-4 gap-2 pt-16 pb-16">
  <h2 class="text-3xl font-bold"><%= country[0]["name"]["official"] %></h2>
  <div class="flex justify-start items-center gap-2 p-2">
    <%= image_tag(country[0]["flags"]["svg"], class: "max-h-[100px] rounded-lg p-2") %>
    <%= image_tag(country[0]["coatOfArms"]["svg"], class: "max-h-[100px] rounded-lg p-2") %>
  </div>
  <div class="flex flex-col gap-2 mt-8 p-4 border rounded-lg">
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Common Name:</h3>
      <span><%= country[0]["name"]["common"] %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Capital City:</h3>
      <span><%= country[0]["capital"].join(" ") %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Region:</h3>
      <span><%= country[0]["region"] %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Subregion:</h3>
      <span><%= country[0]["subregion"] %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Languages:</h3>
      <div class="flex gap-2">
        <% country[0]["languages"].each_pair do |key, value| %>
          <span><%= value %></span>
        <% end %>
      </div>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Latitude/Longitude:</h3>
      <span><%= country[0]["latlng"].join(" ") %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Area:</h3>
      <span><%= country[0]["area"] %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Population:</h3>
      <span><%= country[0]["population"] %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">Timezones:</h3>
      <span><%= country[0]["timezones"].join(" ") %></span>
    </div>
    <div class="flex justify-start gap-2 p-2">
      <h3 class="font-semibold">continents:</h3>
      <span><%= country[0]["continents"].join(" ") %></span>
    </div>
  </div>
</div>

app/views/countries/index.html.erb
<%= turbo_frame_tag "countries" do %>
  <%= render partial: "countries", locals: { countries: @countries } %>
<% end %>

app/views/countries/show.html.erb
<div class="flex flex-col p-8 gap-2 pt-16 pb-16">
  <h2 class="text-4xl font-semibold"><%= @country[0]["name"]["official"] %></h2>
  <div class="flex flex-row-reverse justify-between gap-20">
    <div class="flex flex-col justify-start items-center w-1/3 mt-8 border rounded-lg shadow-sm gap-2 p-8">
      <%= image_tag(@country[0]["flags"]["svg"], class: "w-full rounded-lg p-2") %>
      <%= image_tag(@country[0]["coatOfArms"]["svg"], class: "w-full rounded-lg p-2") if @country[0]["coatOfArms"].present? %>
    </div>
    <div class="flex flex-col gap-2 mt-8 p-4 w-2/3 border rounded-lg shadow-sm">
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Common Name:</h3>
        <span><%= @country[0]["name"]["common"] %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Capital City:</h3>
        <span><%= @country[0]["capital"].join(" ") %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Region:</h3>
        <span><%= @country[0]["region"] %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Subregion:</h3>
        <span><%= @country[0]["subregion"] %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Languages:</h3>
        <div class="flex gap-2">
          <% @country[0]["languages"].each_pair do |key, value| %>
            <span><%= value %></span>
          <% end %>
        </div>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Latitude/Longitude:</h3>
        <span><%= @country[0]["latlng"].join(" ") %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Area:</h3>
        <span><%= @country[0]["area"] %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Population:</h3>
        <span><%= @country[0]["population"] %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">Timezones:</h3>
        <span><%= @country[0]["timezones"].join(" ") %></span>
      </div>
      <div class="flex justify-start gap-2 p-2">
        <h3 class="font-semibold">continents:</h3>
        <span><%= @country[0]["continents"].join(" ") %></span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CountriesDirectory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body data-controller="search-countries">
    <header class="p-10">
      <%= render "shared/header" %>
    </header>

    <%= turbo_frame_tag "toast" %>
    
    <main class="container mx-auto px-5 bg-gray-100">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<% search_categories=["All","Asia","Europe","Africa","Americas","Oceania"]%>
<nav class="border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">        
  <div class="flex justify-center w-full mx-auto">
    <%= form_with url: search_country_path, method: :get, data: { controller: 'auto-submit' }, class: "relative flex" do |f| %>
      <input type="text" data-action="input->auto-submit#submit input->search-countries#inputSearch" name="query" class="flex-grow min-w-full lg:min-w-80 p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-l-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-s-gray-700  dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500" placeholder="Search country name" />
      <button type="submit" class="p-2.5 text-sm font-medium text-white bg-red-700 rounded-r-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
        </svg>
        <span class="sr-only">Search</span>
      </button>
    <% end %>
  </div>
</nav>

app/views/shared/_toast.html.erb
<div data-controller="notification" 
     data-notification-delay-value="2000" 
     class="transition transform duration-1000 hidden fixed flex justify-center top-5 right-5 z-50" 
     data-transition-enter-from="opacity-0 translate-x-6" 
     data-transition-enter-to="opacity-100 translate-x-0" 
     data-transition-leave-from="opacity-100 translate-x-0" 
     data-transition-leave-to="opacity-0 translate-x-6"
>
  <div id="toast-warning" class="flex items-center w-full max-w-sm p-4 text-white bg-red-500 rounded-lg shadow-md dark:text-gray-400 dark:bg-gray-800" role="alert">
    <div class="flex items-center justify-center flex-shrink-0 w-8 h-8 text-orange-500 bg-orange-100 rounded-lg dark:bg-orange-700 dark:text-orange-200">
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM10 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-4a1 1 0 0 1-2 0V6a1 1 0 0 1 2 0v5Z"/>
      </svg>
    </div>
    <div class="ml-3 text-sm font-normal pr-4"><%= message %></div>
    <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-warning" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
      </svg>
    </button>
  </div>
</div>